create extension if not exists pgcrypto;

create table if not exists public.weeg_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  symbols text[] not null,
  macro_timeframe text not null default '4h',
  trend_timeframe text not null default '1h',
  confirmation_timeframe text not null default '15m',
  execution_timeframe text not null default '5m',
  risk_per_trade numeric not null default 0.005,
  minimum_rr numeric not null default 2.0,
  confidence_threshold integer not null default 65,
  updated_at timestamptz not null default now()
);

create table if not exists public.weeg_trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  symbol text not null,
  direction text not null check (direction in ('LONG','SHORT')),
  timeframe text not null,
  signal_time timestamptz not null,
  entry numeric not null,
  stop_loss numeric not null,
  take_profit_1 numeric not null,
  take_profit_2 numeric not null,
  risk_reward numeric not null,
  confidence numeric not null,
  regime text not null,
  structure_state text,
  liquidity_state text,
  fvg_state text,
  volume_state text,
  momentum_state text,
  status text not null default 'OPEN' check (status in ('PENDING','OPEN','PARTIAL','CLOSED','STOPPED','INVALIDATED')),
  result text,
  pnl numeric,
  max_favorable_excursion numeric,
  max_adverse_excursion numeric,
  exit_reason text,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.weeg_trade_events (
  id bigint generated by default as identity primary key,
  trade_id uuid not null references public.weeg_trades(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists weeg_trades_symbol_status_idx on public.weeg_trades(symbol, status);
create index if not exists weeg_trades_signal_time_idx on public.weeg_trades(signal_time desc);
create index if not exists weeg_trade_events_trade_idx on public.weeg_trade_events(trade_id, created_at desc);

alter table public.weeg_settings enable row level security;
alter table public.weeg_trades enable row level security;
alter table public.weeg_trade_events enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_settings' and policyname='weeg settings public read') then
    create policy "weeg settings public read" on public.weeg_settings for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_settings' and policyname='weeg settings public write') then
    create policy "weeg settings public write" on public.weeg_settings for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_trades' and policyname='weeg trades public read') then
    create policy "weeg trades public read" on public.weeg_trades for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_trades' and policyname='weeg trades public write') then
    create policy "weeg trades public write" on public.weeg_trades for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_trade_events' and policyname='weeg events public read') then
    create policy "weeg events public read" on public.weeg_trade_events for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='weeg_trade_events' and policyname='weeg events public write') then
    create policy "weeg events public write" on public.weeg_trade_events for all using (true) with check (true);
  end if;
end $$;
